### ISSUE TITLE
Any chance to have an npm package ?

### ISSUE THREAD

**Issue by bacloud23** [pemistahl/lingua-rs#142]
Thanks a lot :)

**Comment by pemistahl** [comment]
I'm going to work on that in the next few weeks. Please stay tuned.

**Comment by bacloud23** [comment]
hi @pemistahl any follow up ? thanks a lot !

**Comment by pemistahl** [comment]
There will be updates and a NPM package eventually. But it will take time. Remember, I'm doing all of this in my limited spare time. So please be patient and refrain from asking further questions in this matter. As soon as there is progress, the respective open issues will be closed.

**Comment by bacloud23** [comment]
my bad, I didn't intend to demand anything or at least urge, I just wanted to know if this is still an interest of yours.
this is because I also did a research on my side and found one wrap (noted in README) and asked for an update.
Anyway, I'm sorry that I re-asked when you already closed the issue.

Kindly

**Comment by pemistahl** [comment]
It's ok, don't worry. As you might have seen, I'm maintaining 4 implementations of Lingua (Kotlin, Python, Go, Rust). The Python and Go ones are the most recent ones with the newest feature set. I will add all of those features to the Kotlin and Rust implementations as well. Afterwards, I will create an NPM package from the Rust library. It just takes time...
