### ISSUE TITLE
Issue with fragment coordinates inside DetectionResult

### ISSUE THREAD

**Issue by Mrodent** [pemistahl/lingua-rs#268]
I've identified a slight problem with the `DetectionResult`s produced when using the feature `detect_multiple_languages_of`. I do appreciate this is an "experimental" feature, but it probably needs to be addressed.

To obtain the text in these fragments I'm doing this:

```
let mut output_str = format!("document {} self.n_ldocs {} text:\n|{}|\n", self.path_str, self.n_ldocs, ldoc_text);
for detection_result in detection_results {
    let fragment: &str = &ldoc_text[detection_result.start_index()..detection_result.end_index()];
    let confidence = self.handling_framework.language_detector.compute_language_confidence(fragment, detection_result.language());
    if confidence > 0.25 {
        ... // probably sensible language classification
    }
    else {
        ... // may be gibberish, or rather technical or something like that
    }
}	
```

Obviously these are coordinates on the **_bytes_** in the String.

With the above, VERY occasionally, I get a panic.  Examples:
`"thread '<unnamed>' panicked at 'byte index 654 is not a char boundary; it is inside 'ο' (bytes 653..655) of ``ἐυηνεμον: ἐυ \"good\" + ἀνεμος \"wind\". ..."`
or 
`"thread '<unnamed>' panicked at 'byte index 65 is not a char boundary; it is inside '\u{f0fc}' (bytes 64..67) of `` 7.3 ..."`

In processing about 2 million words I only get a handful of panics, and these appear to be on VERY exotic and obscure Unicode: accented Ancient Greek or U+F0FC "Private Use Character".

But the trouble is that, currently, I'm not too sure how to "catch" such a thing before it panics: if a char boundary is violated by `[result.start_index()..result.end_index()]` this does not produce a `Result`, it just panics! And this in turn means that the whole of the rest of the document I'm parsing never gets processed. (My documents are being parsed in parallel threads so other documents are unaffected).

Naturally, I'm trying to find a way to test each proposed slice to find out whether or not it's "legal". But even if I do, obviously this would mean a lot more processing time.

So maybe you might want to think about providing indices on the **chars** rather than the bytes: users could then do this: 

```
let text_vec = whole_string.chars().collect::<Vec<_>>();
fragment = text_vec[detection_result.start_index_of_chars()..detection_result.end_index_of_chars()].iter().cloned().collect::<String>();
```

**Comment by Mrodent** [comment]
Ah, I have found a workaround: first time I've heard about `panic::catch_unwind`:

```
let result = std::panic::catch_unwind(||{
    ...
    for detection_result in detection_results {
    	let fragment: &str = &ldoc_text[detection_result.start_index()..detection_result.end_index()];
	    let confidence = self.handling_framework.language_detector.compute_language_confidence(fragment, detection_result.language());
	    if confidence > 0.25 {
	    	...
	    }
    }	
});
if let Err(e) = result {
	error!("got error: {:#?}", e)
}
```

**Comment by pemistahl** [comment]
The indices are actually supposed to be character indices, not byte indices. It turns out that this is a [bug](https://github.com/rust-lang/regex/issues/1046) in the regex crate which my library uses internally. This bug has been [fixed](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#1100-2023-10-09) since my last release. I'm going to create a new release soon which will use the updated regex crate including this bug fix. Then the errors you are getting now will hopefully be gone.
