### ISSUE TITLE
model.rs panics when creating language model from text that contains multi-byte Unicode characters

### ISSUE THREAD

**Issue by eekkaiia** [pemistahl/lingua-rs#3]
https://github.com/pemistahl/lingua-rs/blob/4e0006327a2cd7457d64be6cb39caae160f8d171/src/model.rs#L135

This line of code resulted in the error below when reading a line containing the character 'ō':

thread 'main' panicked at 'byte index 23 is not a char boundary; it is inside 'ō' (bytes 22..24) of `nau mai haere mai ki tō mātou pae tukutuku. kia kore koe e ngaro taku reo rangatira.`', src/model.rs:135:30

A similar error occurred in the 'compute_relative_frequencies' function at line model.rs:160 for the same reason. I believe these functions iterate through 'line' by byte which doesn't work with the Unicode representation for 'ō'. I noticed  a different approach was used in implementing the 'from' function for 'TestDataLanguageModel' which appears to be a solution that handles multi-byte Unicode correctly: 

model.rs:185:    let slice = &chars[i..i + ngram_length].iter().collect::<String>();

**Comment by pemistahl** [comment]
Thanks @eekkaiia. I'm going to fix this soon.
