### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nathanielsimard** [pemistahl/lingua-rs#32]
First, thanks for your work on Lingua. 

I found a memory leak when using lingua with the tokio runtime. I think the problem comes from the fact that the language detector might be `Send` or `Sync` to multiples threads.

I tried using  `with_preloaded_language_models()` on the builder with no success.
Even when I build a new `LanguageDetector` in each method call I still have a memory leak.

**Comment by pemistahl** [comment]
Hi Nathaniel, thanks for reaching out. Lingua uses [Rayon](https://github.com/rayon-rs/rayon) internally to speed up the probability summation. But Rayon itself is not supposed to cause any data races or memory leaks. Can you please show me some code and any errors or stack traces you get? Without more information, I'm unable to help you.

**Comment by pemistahl** [comment]
@nathanielsimard Since you have not answered anymore, I'm closing this issue now. If you think that your problem still exists, please give me more details. Thank you.
