### ISSUE TITLE
Bug in iso_code_639_3() debug print

### ISSUE THREAD

**Issue by mabushey** [pemistahl/lingua-rs#45]
```
println!("{:?} -- {} -- {:?}", i, i.iso_code_639_3(), i.iso_code_639_3());
Italian -- ita -- ITA
```
Debug print shouldn't be giving a different value than a normal print.

Also it seems impossible to do anything with the value returned:
```
30 |       if i == "Italian" { println!("Match"); }
   |            ^^ no implementation for `Language == str
   
30 |       if i.to_owned() == "Italian" { println!("Match"); }
   |                          ^^^^^^^^^ expected enum `Language`, found `&str`
   
30 |       if i.display() == "Italian" { println!("Match"); }
   |            ^^^^^^^ method not found in `&Language`
```
It appears that we're missing display()... Do I just need to use the strum_macros crate? Should I attempt to make a PR to add the display() trait?

The accuracy is looking really good; I've tested so far with about 50 subtitles (grabbing 10 lines evenly distributed throughout the file) and it's 100% accurate so far. Thanks for such an awesome library, and your help using it. :)

**Comment by mabushey** [comment]
In languages.rs line 25-31:
```
/// This enum specifies the so far 75 supported languages which can be detected by *Lingua*.
#[derive(
    Clone, Debug, Serialize, Deserialize, EnumIter, Eq, PartialEq, Hash, Ord, PartialOrd, EnumString,
)]
#[serde(rename_all(serialize = "UPPERCASE", deserialize = "UPPERCASE"))]
#[strum(ascii_case_insensitive)]
pub enum Language {
```

Is it as simple as adding Display to the derive list (line 26)?

**Comment by pemistahl** [comment]
> Debug print shouldn't be giving a different value than a normal print.

No, both prints serve different purposes, so they return different values. This is not a bug and won't be changed.

The `Display` trait is actually not implemented for the `Language` enum, that's true. I can add this if you want. However, you can perform the comparison like this:

    Language::Italian == Language::from_str("Italian").unwrap()

The comparison is case-insensitive, so It is also valid to pass the language string entirely in lowercase or uppercase.

> Thanks for such an awesome library, and your help using it. :)

You are welcome. :) I appreciate your feedback. I'm happy that my library is useful for quite some people.
