### ISSUE TITLE
feature flag to disable wasm

### ISSUE THREAD

**Issue by zacharywhitley** [pemistahl/lingua-rs#59]
Oddly I had to add a feature flag to lingua-rs to *disable* wasm so that I could use it in a WebAssembly project. It was't actually disabling wasm as much as it's disabling the wasm-bindgen. I'm running it in a non-browser setting and the code generated from bindgen causes problems. Let me know if you'd like me to put in a PR. It was only a couple of minor changes.

**Comment by pemistahl** [comment]
Hi Zachary, I thought that wasm-bindgen would just generate the JavaScript bindings. Does it modify the wasm file itself, too? What exactly are your problems?

And yes, please open a PR. I'm busy doing other stuff in the next days. Thank you.

**Comment by zacharywhitley** [comment]
It brought in some dependencies on JSVar that I wouldn't have in my environment. I'll put together a PR. Thanks.

**Comment by pemistahl** [comment]
@zacharywhitley Do you still plan to open a PR for this issue? If not, I will close it because it's not clear to me what your exact problems were with the current WASM implementation. Perhaps you want to clarify. Thanks.
