### ISSUE TITLE
Significant startup time

### ISSUE THREAD

**Issue by lhr0909** [pemistahl/lingua-rs#7]
Hi,

I am trying to embed this into my program but I am seeing a very long startup time setting up the detector. Can I ask (on the high level) why that is (other than the files being larger than other libraries due to the use of 5-grams). Anything we can do to speed up the initialization time?

Happy to help contribute if needed.

**Comment by pemistahl** [comment]
Hello Simon,

thanks for your request. 

The long startup time is because the language models are loaded into memory. This happens lazily, that is, only if the statistical approach is necessary to determine the language of the input text. The rule-based engine is sometimes enough to determine the language. In such a case, no language models would have to be loaded. 

You can speed up the loading process by building the detector from fewer languages instead of simply taking all of them. However, of course, this limits the languages the detector can recognize. 

I plan to experiment with multithreading to speed up the loading process even more.

Does that answer your question?

**Comment by lhr0909** [comment]
Yeah it does. Thank you! I have tried to load just English and Turkish models, and it still takes about 3 minutes to initialize. (running `Builder.build()` with just 2 languages).

I am checking the possible spots where we can potentially drop in rayon to speed things up, and I can see the lazy initialization of the n-gram models. One of the places I found is [here](https://github.com/pemistahl/lingua-rs/blob/master/src/detector.rs#L63). But my gut tells me that can't just be it.

For your reference, here is what I am building: https://github.com/xanthous-tech/lingua-node . I am planning to wrap it as a NodeJS library for my slack NodeJS bot that needs language detection. Seems to me that I will need to put the entire thing to another thread and wait for it to unblock.

**Comment by pemistahl** [comment]
Three minutes for only two languages? This is weird. Did you build my library in debug mode or in release mode? In debug mode, loading the language models takes a pretty long time indeed. But in release mode, it is very quick.

I don't know a lot about NodeJS. But I will gladly check out your project later and take a look. Perhaps I can find out what's causing the slow performance. I'll let you know.

**Comment by lhr0909** [comment]
This is the time spent with release build native module running in the NodeJS wrapper. I can certainly live with that, but I would definitely want to see if there are places we can still optimize here. Since in NodeJS this blocks any execution, the only thing I can do is to rely on worker threads, so it is not as fun as wrapping it in tokio etc. 😄 

![image](https://user-images.githubusercontent.com/1154575/101762364-523e4a80-3b18-11eb-9969-52080a1cd66e.png)

**Comment by lhr0909** [comment]
Closing for now. But thank you for the swift turnaround! [the library](https://github.com/xanthous-tech/lingua-node) is properly wrapped with safe APIs. Gotta love Rust!

**Comment by pemistahl** [comment]
You are welcome, Simon. 🙂

I develop on a very performant iMac and I have not tested the loading times on other machines, so I'm sure what's quick for me might be slow for other users. I've been planning to run some benchmarks anyway and I'm sure there is room for improvement. 

Feel free to send me a pull request in case you can provide some optimizations. Always appreciated. 🙂

**Comment by pemistahl** [comment]
@lhr0909 I think I was able to speed up the language model loading process using parallel iterators provided by the Rayon library. Please take a look at commit f9795eb4e976246b1e61cc3992de34fef8d0fdd0 in the development branch for the next release 1.1.0.

Before this change, running all accuracy reports took 460 seconds on my machine. Afterwards, it only took 182 seconds. Pretty good, huh? Please let me know what you think.
