### ISSUE TITLE
Failing to compile lingua 1.0.2

### ISSUE THREAD

**Issue by luananama** [pemistahl/lingua-rs#9]
When trying to run a file that uses lingua 1.0.2 as a dependency, compiling fails with the following error. This is a new rust project, with no other dependencies and just a println, as I just wanted to check out the library 
```
Compiling lingua v1.0.2
error[E0603]: module `export` is private
   --> C:\Users\luana\.cargo\registry\src\github.com-1ecc6299db9ec823\lingua-1.0.2\src\ngram.rs:19:12
    |
19  | use serde::export::Formatter;
    |            ^^^^^^ private module
    |
note: the module `export` is defined here
   --> C:\Users\luana\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.119\src\lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0603`.
error: could not compile `lingua`.
```

**Comment by pemistahl** [comment]
Shit, this was not found by all the unit tests. It made my library basically unusable and nobody told me until today. :( Thank you so much for telling me @luananama. I've just fixed it. Please try it again with version 1.0.3.

**Comment by GrayJack** [comment]
@pemistahl It is possible to create a folder called `tests` that `cargo test` will run all code inside it. It is often used to test the public API of the crate, since code there behaves as a separate crate, so you have to import stuff like a user of the library should use.

**Comment by pemistahl** [comment]
@GrayJack The funny (or rather sad) thing is, this came to my mind yesterday and I tried that. But the bug did not occur in the integration test. Only when creating a brand-new Rust project and adding Lingua as a dependency, I could reproduce the problem. This is very annoying. Anyway, it is fixed now and I will know better in the future. 

Thank you for your concern.
